name: gisandbox
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - gdal
  - fiona  
  - rasterio
  - pip:
    - numpy
    - scipy
    - pandas
    - keplergl
    - geopandas
    - shapely
    - folium
    - pysal
    - matplotlib
    - netCDF4
    - rtree
    - sklearn
    - keras
    - tensorflow
